perfeito, agora arrume esse:
FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/saas-fitness1/firestore/indexes?create_composite=ClZwcm9qZWN0cy9zYWFzLWZpdG5lc3MxL2RhdGFiYXNlcy8oZGVmYXVsdCkvY29sbGVjdGlvbkdyb3Vwcy91c2VyUHJvZ3Jlc3NMb2dzL2luZGV4ZXMvXxABGgoKBnVzZXJJZBABGggKBGRhdGUQAhoMCghfX25hbWVfXxAC